import { TeamMember, Project, Event, Sponsor } from './types';

export const NAV_LINKS = [
  { name: 'HOME', path: '/' },
  { name: 'ABOUT', path: '/about' },
  { name: 'PROJECTS', path: '/projects' },
  { name: 'EVENTS', path: '/events' },
  { name: 'SPONSORS', path: '/sponsors' },
];

export const EXEC_BOARD: TeamMember[] = [
  {
    id: '1',
    name: 'George Kuney',
    position: 'President',
    year: 'Junior',
    major: 'Mechanical Engineering',
    hometown: '',
    funFact: 'I built a Voron',
    imageUrl: 'https://picsum.photos/seed/george-kuney/300/300',
    isExec: true,
    email: 'gmk5561@psu.edu',
  },
  {
    id: '2',
    name: 'Hady Diab',
    position: 'Vice President',
    year: 'Senior',
    major: 'Mechanical Engineering',
    hometown: '',
    funFact: 'GO EAGLES',
    imageUrl: 'https://picsum.photos/seed/hady-diab/300/300',
    isExec: true,
    email: 'hxd5237@psu.edu',
  },
  {
    id: '3',
    name: 'Henry Rumbaugh',
    position: 'Treasurer',
    year: 'Sophomore',
    major: 'Mechanical Engineering',
    hometown: '',
    funFact: 'I am a certified drone pilot',
    imageUrl: 'https://picsum.photos/seed/henry-rumbaugh/300/300',
    isExec: true,
    email: 'hjr5365@psu.edu',
  },
  {
    id: '4',
    name: 'Catherine Boss',
    position: 'Secretary',
    year: 'Junior',
    major: 'Mechanical Engineering',
    hometown: '',
    funFact: '',
    imageUrl: 'https://picsum.photos/seed/catherine-boss/300/300',
    isExec: true,
    email: 'jcb6560@psu.edu',
  },
  {
    id: '5',
    name: 'Joseph Northcode',
    position: 'Corporate Outreach Lead',
    year: 'Sophomore',
    major: 'Mechanical Engineering',
    hometown: '',
    funFact: 'I race triathlons.',
    imageUrl: 'https://picsum.photos/seed/joseph-northcode/300/300',
    isExec: true,
    email: 'jjn5654@psu.edu',
  },
  {
    id: '6',
    name: 'Michael O\'Neill',
    position: 'THON Chair',
    year: 'Junior',
    major: 'Mechanical Engineering',
    hometown: '',
    funFact: 'West Philadelphia born and raised',
    imageUrl: 'https://picsum.photos/seed/michael-oneill/300/300',
    isExec: true,
    email: 'mqo5343@psu.edu',
  },
  {
    id: '7',
    name: 'Mitchell Goldman',
    position: 'Design Director',
    year: 'Junior',
    major: 'Mechanical Engineering',
    hometown: '',
    funFact: 'I built a zipline in my backyard from scratch',
    imageUrl: 'https://picsum.photos/seed/mitchell-goldman/300/300',
    isExec: true,
    email: 'mag7140@psu.edu',
  },
  {
    id: '8',
    name: 'Sam Schulson',
    position: 'Internal Outreach',
    year: 'Senior',
    major: 'Mechanical Engineering',
    hometown: '',
    funFact: 'Big soccer fan',
    imageUrl: 'https://picsum.photos/seed/sam-schulson/300/300',
    isExec: true,
    email: 'sbs6746@psu.edu',
  },
  {
    id: '9',
    name: 'Ellena Fox',
    position: 'Events Coordinator',
    year: 'Junior',
    major: 'Mechanical Engineering',
    hometown: '',
    funFact: '',
    imageUrl: 'https://picsum.photos/seed/ellena-fox/300/300',
    isExec: true,
    email: 'emf5833@psu.edu',
  },
  {
    id: '10',
    name: 'Anthony Dangio',
    position: 'Events Coordinator',
    year: 'Senior',
    major: 'Mechanical Engineering',
    hometown: '',
    funFact: 'I had 2 peacocks as pets',
    imageUrl: 'https://picsum.photos/seed/anthony-dangio/300/300',
    isExec: true,
    email: 'abd5904@psu.edu',
  },
  {
    id: '11',
    name: 'Parker Loose',
    position: 'Logistics Officer',
    year: 'Sophomore',
    major: 'Mechanical Engineering',
    hometown: '',
    funFact: 'I typically read 100 books a year',
    imageUrl: 'https://picsum.photos/seed/parker-loose/300/300',
    isExec: true,
    email: 'phl5071@psu.edu',
  },
  {
    id: '12',
    name: 'Landon Zimmerman',
    position: 'Design Director',
    year: 'Sophomore',
    major: 'Mechanical Engineering',
    hometown: '',
    funFact: 'I like Battlebots',
    imageUrl: 'https://picsum.photos/seed/landon-zimmerman-exec/300/300',
    isExec: true,
    email: 'lcz5044@psu.edu',
  },
  {
    id: '13',
    name: 'Zander Catterton',
    position: 'Logistics Officer',
    year: 'Senior',
    major: 'Mechanical Engineering',
    hometown: '',
    funFact: 'I like CAD',
    imageUrl: 'https://picsum.photos/seed/zander-catterton/300/300',
    isExec: true,
    email: 'zcc5047@psu.edu',
  },
];

export const DESIGN_TEAM: TeamMember[] = [
    { id: 'd1', name: 'Zander Catterton', position: 'Logistics Officer', year: 'Senior', major: 'Mechanical Engineering', hometown: '', funFact: 'I like CAD', imageUrl: 'https://picsum.photos/seed/zander-catterton-design/300/300', isExec: false, email: 'zcc5047@psu.edu' },
    { id: 'd2', name: 'Landon Zimmerman', position: 'Design Director', year: 'Sophomore', major: 'Mechanical Engineering', hometown: '', funFact: 'I\'ve been to 5 national parks within a week', imageUrl: 'https://picsum.photos/seed/landon-zimmerman/300/300', isExec: false, email: 'lcz5044@psu.edu' },
    { id: 'd3', name: 'Mitchell Goldman', position: 'Design Team Director', year: 'Junior', major: 'Mechanical Engineering', hometown: '', funFact: 'I built a zipline in my backyard from scratch', imageUrl: 'https://picsum.photos/seed/mitchell-goldman-design/300/300', isExec: false, email: 'mag7140@psu.edu' },
    { id: 'd4', name: 'George Kuney', position: 'President', year: 'Junior', major: 'Mechanical Engineering', hometown: '', funFact: 'I built a Voron', imageUrl: 'https://picsum.photos/seed/george-kuney-design/300/300', isExec: false, email: 'gmk5561@psu.edu' },
    { id: 'd5', name: 'Henry Rumbaugh', position: 'Drone Project Lead', year: 'Sophomore', major: 'Mechanical Engineering', hometown: '', funFact: 'I have a commercial drone pilot\'s license', imageUrl: 'https://picsum.photos/seed/henry-rumbaugh-design/300/300', isExec: false, email: 'hjr5365@psu.edu' },
    { id: 'd6', name: 'Tom Moore', position: 'BattleBots Lead', year: 'Sophomore', major: 'Mechanical Engineering', hometown: '', funFact: 'I am in a country band', imageUrl: 'https://picsum.photos/seed/tom-moore/300/300', isExec: false, email: 'tjm7333@psu.edu' },
    { id: 'd7', name: 'Logan Alefantis', position: 'BattleBots Team Lead', year: 'Senior', major: 'Mechanical Engineering', hometown: '', funFact: 'I\'ve been to 44/50 states', imageUrl: 'https://picsum.photos/seed/logan-alefantis/300/300', isExec: false, email: 'lca5226@psu.edu' },
    { id: 'd8', name: 'Cole Thomas', position: 'BattleBots Lead', year: 'Junior', major: 'Mechanical Engineering', hometown: '', funFact: 'Born in Alaska', imageUrl: 'https://picsum.photos/seed/cole-thomas/300/300', isExec: false, email: 'cat5992@psu.edu' },
];

export const GENERAL_BODY_MEMBERS: TeamMember[] = DESIGN_TEAM;

export const PROJECTS: Project[] = [
  {
    id: '1',
    title: 'Assistive Tech',
    description: 'A universally attachable device to glasses that picks up audio in real time to (translate it, if needed and) display it on a mini-screen in front of the user to allow for smoother communication with people with hearing disabilities and/or people who don\'t speak certain languages.',
    imageUrl: 'https://picsum.photos/seed/assistive-tech/800/400',
    chairs: [
      { name: 'Elliott', role: 'Member' },
      { name: 'Parth', role: 'Member' },
      { name: 'Carter', role: 'Member' },
      { name: 'Aarav', role: 'Member' },
      { name: 'Liam', role: 'Member' },
      { name: 'Abhinay', role: 'Member' },
      { name: 'Samarth', role: 'Member' },
      { name: 'Youssef', role: 'Member' },
      { name: 'Raphael', role: 'Member' },
      { name: 'Zach', role: 'Member' },
      { name: 'Laetitia', role: 'Member' },
      { name: 'Candy', role: 'Member' },
      { name: 'Anna', role: 'Member' },
      { name: 'Shusti', role: 'Member' },
      { name: 'Ethan', role: 'Member' },
      { name: 'Jacob', role: 'Member' },
    ],
    status: 'current',
  },
  {
    id: '2',
    title: 'Project Impact',
    description: 'We are competing in ASME\'s national Student Design Challenge by creating a small robot "trash truck" capable of navigating a model city, collecting both trash and recycling, sorting the materials, and delivering them to the correct disposal sites. The device must handle varied terrain, operate quickly and accurately, and demonstrate a complete end-to-end waste collection process.',
    imageUrl: 'https://picsum.photos/seed/project-impact/800/400',
    chairs: [],
    status: 'current',
  },
  {
    id: '3',
    title: 'Hovercraft',
    description: 'Building RC Hovercrafts to compete in an intense competition where the fastest and most maneuverable craft wins.',
    imageUrl: 'https://picsum.photos/seed/hovercraft/800/400',
    chairs: [
      { name: 'George Kuney', role: 'Project Lead' },
      { name: 'George Kuney', role: 'Deltamorph Team Lead (1st place)' },
      { name: 'Mitchell Goldman', role: 'Team Lead (2nd Place)' },
      { name: 'Nick Bucher', role: 'Team Lead (3rd Place)' },
    ],
    status: 'past',
  },
];

export const EVENTS: Event[] = [
  {
    id: '1',
    title: 'THON Fundraiser',
    date: 'Coming Soon',
    description: 'Help support THON and make a difference!',
    type: 'upcoming',
    imageUrl: 'https://picsum.photos/seed/thon/300/300',
  },
  {
    id: '2',
    title: 'General Body Meeting',
    date: 'Coming Soon',
    description: 'Join us for updates on projects and upcoming events.',
    type: 'this_week',
  },
  {
    id: '3',
    title: 'Design Team Meeting',
    date: 'Coming Soon',
    description: 'Work on exciting projects with the design team.',
    type: 'upcoming',
    imageUrl: 'https://picsum.photos/seed/design-team/300/300',
  },
  {
    id: '4',
    title: 'Project Meeting',
    date: 'Ongoing',
    description: 'Regular meetings for current projects.',
    type: 'upcoming',
    imageUrl: 'https://picsum.photos/seed/project-meeting/300/300',
  },
  {
    id: '5',
    title: 'Social Event',
    date: 'Coming Soon',
    description: 'Join us for fun social activities!',
    type: 'upcoming',
    imageUrl: 'https://picsum.photos/seed/social/300/300',
  },
  {
    id: '6',
    title: 'Past Event',
    date: '2024-2025',
    description: 'Thank you to everyone who participated in our past events.',
    type: 'past',
  },
];

export const SPONSORS: Sponsor[] = [
    { id: '1', name: 'Autodesk', logoUrl: 'https://picsum.photos/seed/autodesk/200/200' },
    { id: '2', name: 'Boeing', logoUrl: 'https://picsum.photos/seed/boeing/200/200' },
    { id: '3', name: 'Lockheed Martin', logoUrl: 'https://picsum.photos/seed/lockheed/200/200' },
    { id: '4', name: 'Shell', logoUrl: 'https://picsum.photos/seed/shell/200/200' },
    { id: '5', name: 'Williams', logoUrl: 'https://picsum.photos/seed/williams/200/200' },
    { id: '6', name: 'Naval Nuclear Lab', logoUrl: 'https://picsum.photos/seed/naval/200/200' },
];
